version: 0.1

environment_variables:
  plaintext:
    key: "value"
phases:
  install:
    commands:
      - echo $key
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - pwd
      - ls
      - ls ./public
      - ls public
      - ls public/dist
artifacts:
  files:
    - ./public/dist/sdk.js
  discard-paths: yes
